export const metadata = {
  title: "Sign In To AI Notes Taking App, it combines speed, security, and intelligence. Stay organized with AI Productivity Tools, seamless Cloud Notes SaaS, and real-time syncing. Perfect for AI Note-Taking for Students, AI Notes for Professionals, and anyone who wants smarter, faster, and more reliable note-taking AI-Powered Notes Taking App | Smart, Fast & Organized Note-Taking",
  description: "You Can Sign In If Your Email is alredy registered and Our AI Notes Taking SaaS app helps you capture, organize, and summarize ideas instantly. Powered by Next.js and AI technology, it allows students, professionals, and teams to boost productivity with smart note organization, instant summaries, cloud sync, and easy sharing. Whether you’re studying, working, or collaborating, our AI-powered notes app keeps everything structured, searchable, and accessible anytime. I-powered SaaS notes app built with Next.js. Create, organize, and summarize notes instantly for students, teams, and professionals. Smart AI Notes Taking App for productivity. Take notes, auto-summarize, organize ideas & collaborate – powered by Next.js SaaS platform.Boost your productivity with our AI Notes Taking SaaS app. Built with Next.js, it helps you capture ideas, summarize instantly, and organize notes effortlessly. Perfect for students, professionals, and teams who need smart, cloud-based note management. Transform the way you take notes with our AI-powered SaaS app. Enjoy intelligent features like note summarization, cloud sync, instant search, and team collaboration. Built on Next.js, it’s fast, secure, and designed to keep your ideas organized. Our AI Notes Taking SaaS app is designed to make note-taking smarter, faster, and more organized. Powered by advanced AI and developed with Next.js, it helps you capture ideas instantly, auto-generate summaries, and keep your notes structured in one place. Whether you are a student writing study notes, a professional organizing tasks, or a team managing projects, our app gives you the tools to stay productive and efficient. With cloud storage, real-time syncing, and AI-driven features like smart search, summarization, and categorization, you’ll never lose track of important information again. Accessible anytime, anywhere, our SaaS platform is the perfect blend of simplicity, speed, and intelligence for modern note-taking. AI Notes Taking Website Next.js SaaS Notes App Smart Notes with AI Cloud Notes & Summaries AI Writing & Note Organizer Best AI Notes App Productivity SaaS Tools Digital Note-Taking Software AI for Students & Professionals Online Notes with AI Summarizer.AI Notes App AI-Powered Notes Taking SaaS Notes App Next.js Notes App Smart Note Taking App Online Notes Organizer AI Productivity Tool Note Summarizer with AI AI Note-Taking for Students Cloud Notes SaaS AI Notes for Professionals Best Notes App",
  keywords: "AI Notes Taking Website Next.js SaaS Notes App Smart Notes with AI Cloud Notes & Summaries AI Writing & Note Organizer Best AI Notes App 2025 Productivity SaaS Tools Digital Note-Taking Software AI for Students & Professionals Online Notes with AI Summarizer AI Notes App AI-Powered Notes Taking SaaS Notes App Next.js Notes App Smart Note Taking App Online Notes Organizer AI Productivity Tool Note Summarizer with AI AI Note-Taking for Students Cloud Notes SaaS AI Notes for Professionals Best Notes App 2025"
};

export default function RootLayout({ children }) {
  return (
            <>
              
          {children}
            </>
  )
}
