"use client";


import { useState } from 'react';
import { Button } from "@/components/ui/button";
import { 
  ChevronDown, 
  ChevronUp,
  HelpCircle,
  Sparkles,
  ArrowRight,
  FileText,
  Globe,
  Shield,
  BookOpen,
  Zap
} from "lucide-react";

const FAQSection = () => {
  const [openIndex, setOpenIndex] = useState(0);

  const faqs = [
    {
      question: "How does it work?",
      answer: "AI Notes Taker uses advanced artificial intelligence to process your documents and content. Simply upload your PDFs, documents, or text, and our AI will automatically extract key information, create summaries, generate notes, and provide intelligent insights. The platform learns from your usage patterns to provide increasingly personalized assistance over time.",
      icon: <Zap className="h-5 w-5" />
    },
    {
      question: "Which type of files are supported?",
      answer: "We support a wide range of file formats including PDFs, Word documents (.doc, .docx), PowerPoint presentations (.ppt, .pptx), Excel spreadsheets (.xls, .xlsx), plain text files (.txt), and images with text (.jpg, .png, .gif). Our AI can extract and process text from scanned documents and images using OCR technology.",
      icon: <FileText className="h-5 w-5" />
    },
    {
      question: "Do you support other languages?",
      answer: "Yes! AI Notes Taker supports over 50 languages including English, Spanish, French, German, Chinese, Japanese, Korean, Arabic, Hindi, and many more. Our AI can process, summarize, and generate notes in multiple languages, making it perfect for international users and multilingual content.",
      icon: <Globe className="h-5 w-5" />
    },
    {
      question: "Can I use the content generated for educational or commercial purposes?",
      answer: "Absolutely! All content generated by AI Notes Taker is yours to use for any purpose - educational, commercial, or personal. We provide you with full rights to the AI-generated content, summaries, and notes. However, we recommend reviewing and customizing the content to ensure it meets your specific needs and requirements.",
      icon: <BookOpen className="h-5 w-5" />
    },
    {
      question: "Are my notes and documents secure?",
      answer: "Security is our top priority. We use enterprise-grade encryption (AES-256) to protect your data both in transit and at rest. All documents are processed securely, and we never store your original files permanently. Our platform is SOC 2 compliant and follows strict data protection regulations. You have complete control over your data and can delete it at any time.",
      icon: <Shield className="h-5 w-5" />
    }
  ];

  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? -1 : index);
  };

  return (
    <section className="relative py-20 bg-white dark:bg-gray-900">
      {/* Background Pattern */}
      <div className="absolute inset-0 bg-grid-pattern opacity-5"></div>
      
      <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header Section */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center px-4 py-2 rounded-full bg-gradient-to-r from-blue-100 to-purple-100 dark:from-blue-900/30 dark:to-purple-900/30 text-blue-800 dark:text-blue-300 text-sm font-medium mb-6">
            <HelpCircle className="h-4 w-4 mr-2" />
            Get Your Questions Answered
          </div>
          
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900 dark:text-white mb-6">
            Frequently Asked
            <span className="block bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              Questions
            </span>
          </h2>
          
          <p className="text-lg text-gray-600 dark:text-gray-300 max-w-3xl mx-auto leading-relaxed">
            Find answers to common questions about AI Notes Taker. Can't find what you're looking for? 
            Contact our support team for personalized assistance.
          </p>
        </div>

        {/* FAQ Accordion */}
        <div className="space-y-4 mb-16">
          {faqs.map((faq, index) => (
            <div 
              key={index}
              className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full px-6 py-6 text-left focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-inset transition-all duration-200"
                aria-expanded={openIndex === index}
                aria-controls={`faq-content-${index}`}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-4">
                    <div className="flex-shrink-0 w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center text-white">
                      {faq.icon}
                    </div>
                    <h3 className="text-lg font-semibold text-gray-900 dark:text-white pr-4">
                      {faq.question}
                    </h3>
                  </div>
                  <div className="flex-shrink-0">
                    {openIndex === index ? (
                      <ChevronUp className="h-6 w-6 text-gray-500 dark:text-gray-400 transition-transform duration-200" />
                    ) : (
                      <ChevronDown className="h-6 w-6 text-gray-500 dark:text-gray-400 transition-transform duration-200" />
                    )}
                  </div>
                </div>
              </button>
              
              <div
                id={`faq-content-${index}`}
                className={`overflow-hidden transition-all duration-300 ease-in-out ${
                  openIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
                }`}
                aria-hidden={openIndex !== index}
              >
                <div className="px-6 pb-6">
                  <div className="border-t border-gray-200 dark:border-gray-700 pt-6">
                    <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                      {faq.answer}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Additional Help Section */}
        <div className="bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 rounded-3xl p-8 md:p-12 text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-blue-500 to-purple-600 rounded-2xl text-white mb-6">
            <Sparkles className="h-8 w-8" />
          </div>
          
          <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
            Still Have Questions?
          </h3>
          
          <p className="text-gray-600 dark:text-gray-300 mb-8 max-w-2xl mx-auto leading-relaxed">
            Our support team is here to help you get the most out of AI Notes Taker. 
            We're available 24/7 to answer any questions and provide personalized assistance.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              size="lg" 
              className="group bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white px-8 py-3 text-lg font-semibold shadow-lg hover:shadow-xl transition-all duration-300"
            >
              Contact Support
              <ArrowRight className="h-5 w-5 ml-2 group-hover:translate-x-1 transition-transform duration-200" />
            </Button>
            
            <Button 
              variant="outline" 
              size="lg" 
              className="group border-2 border-gray-300 dark:border-gray-600 px-8 py-3 text-lg font-semibold hover:bg-gray-50 dark:hover:bg-gray-800 transition-all duration-300"
            >
              View Documentation
            </Button>
          </div>
        </div>

        {/* Quick Stats */}
        <div className="mt-16 grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="text-3xl font-bold text-blue-600 dark:text-blue-400 mb-2">24/7</div>
            <div className="text-sm text-gray-600 dark:text-gray-400">Support Available</div>
          </div>
          <div className="text-center">
            <div className="text-3xl font-bold text-purple-600 dark:text-purple-400 mb-2">5min</div>
            <div className="text-sm text-gray-600 dark:text-gray-400">Average Response Time</div>
          </div>
          <div className="text-center">
            <div className="text-3xl font-bold text-green-600 dark:text-green-400 mb-2">98%</div>
            <div className="text-sm text-gray-600 dark:text-gray-400">Customer Satisfaction</div>
          </div>
        </div>
      </div>

      {/* Floating Elements */}
      <div className="absolute top-20 left-10 hidden lg:block">
        <div className="w-16 h-16 bg-blue-200 dark:bg-blue-800 rounded-full opacity-20 animate-pulse"></div>
      </div>
      <div className="absolute bottom-20 right-10 hidden lg:block">
        <div className="w-12 h-12 bg-purple-200 dark:bg-purple-800 rounded-full opacity-20 animate-pulse delay-1000"></div>
      </div>
    </section>
  );
};

export default FAQSection;
